# Generated by Django 2.2.15 on 2020-08-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200827_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='work_experience',
            field=models.TextField(default='Enter Work Experience'),
        ),
    ]
