# Generated by Django 2.2.15 on 2020-08-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_cv_work_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='projects',
            field=models.TextField(default='Enter Projects'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='address',
            field=models.CharField(default='Enter Address', max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='email',
            field=models.EmailField(default='enter@email.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='cv',
            name='phone_number',
            field=models.CharField(default='Enter', max_length=11),
        ),
    ]
